class AppStrings {
  static const String englishCode = 'en';
  static const String soraniCode = 'ckb';

  static const Map<String, String> soraniPhrases = {
    'Attendance History': 'مێژووی ئامادەبوون',
    'View and filter your past attendance records':
        'تۆمارەکانی ئامادەبوونی پێشووت ببینە و پالێوریان بکە',
    'All Dates': 'هەموو بەروارەکان',
    'All': 'هەموو',
    'Present': 'ئامادە',
    'Late': 'دواکەوتوو',
    'Absent': 'غایب',
    'Clear Filters': 'سڕینەوەی پالێوەرەکان',
    'Failed to load history': 'بارکردنی مێژوو سەرکەوتوو نەبوو',
    'No records found': 'هیچ تۆمارێک نەدۆزرایەوە',
    'Try adjusting your filters': 'هەوڵبدە پالێوەرەکان بگۆڕیت',
    'Retry': 'دووبارە هەوڵبدە',
    'Date': 'بەروار',
    'Day': 'ڕۆژ',
    'Status': 'دۆخ',
    'Time': 'کات',
    'Confidence': 'متمانە',
    'Checked in at {time}': 'تۆمارکراوە لە {time}',
    'Mark Attendance': 'تۆمارکردنی ئامادەبوون',
    'Mark your attendance with facial recognition':
        'بە ناسینەوەی ڕوو ئامادەبوونەکەت تۆمار بکە',
    'No face registered': 'هیچ ڕووێک تۆمار نەکراوە',
    'Please register your face before marking attendance':
        'تکایە پێش تۆمارکردنی ئامادەبوون ڕووت تۆمار بکە',
    'Register Face': 'تۆمارکردنی ڕوو',
    'Camera Preview': 'پێشبینی کامێرا',
    'Position your face in the frame': 'ڕووت لە ناو چوارچێوەکەدا ڕێک بخە',
    'Ready to scan': 'ئامادەی پشکنین',
    'Scanning...': 'پشکنین دەکرێت...',
    'Capture & Mark Attendance': 'وێنە بگرە و ئامادەبوون تۆمار بکە',
    'Attendance already marked today': 'ئامادەبوونت ئەمڕۆ پێشتر تۆمار کراوە',
    'Check Out': 'چوونەدەرەوە',
    'Register Your Face': 'ڕووت تۆمار بکە',
    'Rotate Camera': 'سوڕاندنی کامێرا',
    'Skip': 'بازدان',
    'Face registered successfully!': 'ڕوو بە سەرکەوتوویی تۆمار کرا!',
    'Capture': 'گرتن',
    'Capturing...': 'وێنە دەگیردرێت...',
    'Update Password': 'نوێکردنەوەی وشەی نهێنی',
    'Choose a strong password to keep your account secure.':
        'وشەی نهێنییەکی بەهێز هەڵبژێرە بۆ پاراستنی هەژمارەکەت.',
    'Current Password': 'وشەی نهێنیی ئێستا',
    'Enter your current password': 'وشەی نهێنیی ئێستات بنووسە',
    'Please enter your current password': 'تکایە وشەی نهێنیی ئێستات بنووسە',
    'New Password': 'وشەی نهێنیی نوێ',
    'Enter new password (min 6 characters)':
        'وشەی نهێنیی نوێ بنووسە (لانیکەم ٦ پیت)',
    'Please enter a new password': 'تکایە وشەی نهێنیی نوێ بنووسە',
    'New password must differ from the current one':
        'وشەی نهێنیی نوێ دەبێت جیاواز بێت لە وشەی ئێستا',
    'Confirm New Password': 'دڵنیابوونەوەی وشەی نهێنیی نوێ',
    'Re-enter your new password': 'وشەی نهێنیی نوێ دووبارە بنووسە',
    'Please confirm your new password': 'تکایە وشەی نهێنیی نوێ پشتڕاست بکەرەوە',
    'Passwords do not match': 'وشەکانی نهێنی یەک ناگرن',
    'Password changed successfully!': 'وشەی نهێنی بە سەرکەوتوویی گۆڕدرا!',
    'Failed to change password': 'گۆڕینی وشەی نهێنی سەرکەوتوو نەبوو',
    'Weak': 'لاواز',
    'Fair': 'مامناوەند',
    'Good': 'باش',
    'Strong': 'بەهێز',
    'Edit Profile': 'دەستکاریکردنی پرۆفایل',
    'Full Name': 'ناوی تەواو',
    'Enter your full name': 'ناوی تەواوت بنووسە',
    'Please enter your full name': 'تکایە ناوی تەواوت بنووسە',
    'Department': 'بەش',
    'Enter your department': 'بەشەکەت بنووسە',
    'Phone Number': 'ژمارەی مۆبایل',
    'Enter your phone number': 'ژمارەی مۆبایلەکەت بنووسە',
    'Save Changes': 'پاشەکەوتکردنی گۆڕانکارییەکان',
    'Profile updated successfully': 'پرۆفایل بە سەرکەوتوویی نوێ کرایەوە',
    'Failed to update profile': 'نوێکردنەوەی پرۆفایل سەرکەوتوو نەبوو',
    'Forgot Password': 'وشەی نهێنی لەبیرکردووە',
    'Reset Password': 'نوێکردنەوەی وشەی نهێنی',
    'Send Reset Email': 'ناردنی ئیمەیڵی نوێکردنەوە',
    'Back to Login': 'گەڕانەوە بۆ چوونەژوورەوە',
    'Notifications': 'ئاگادارکردنەوەکان',
    'No notifications yet': 'هێشتا هیچ ئاگادارکردنەوەیەک نییە',
    'Mark all as read': 'هەمووی وەک خوێندراوە نیشان بدە',
    "You're all caught up!": 'هەموو شتێکت خوێندۆتەوە!',
    'System': 'سیستەم',
    'Alert': 'ئاگاداری',
    'Late Check-In': 'هاتنەژوورەوەی دواکەوتوو',
    'Low Attendance Warning': 'ئاگاداریی کەمی ئامادەبوون',
    'New Leave Request': 'داواکاریی مۆڵەتی نوێ',
    'Leave Request Approved': 'داواکاریی مۆڵەت پەسەند کرا',
    'Leave Request Rejected': 'داواکاریی مۆڵەت ڕەت کرایەوە',
    'Approved': 'پەسەندکراو',
    'Rejected': 'ڕەتکراوە',
    'You have been marked late today at {time}.':
        'ئەمرۆ لە {time} وەک دواکەوتوو تۆمار کرایت.',
    'Your attendance is {percent}%, which is below the {threshold}% threshold.':
        'ڕێژەی ئامادەبوونت {percent}% ـە، کە لە خوار سنووری {threshold}% ـەوەیە.',
    '{name} submitted a leave request for {date}.':
        '{name} داواکاریی مۆڵەتی بۆ {date} ناردووە.',
    'Your leave request for {date} was {status}.':
        'داواکاریی مۆڵەتەکەت بۆ {date} {status}.',
    'Your leave request for {date} was {status}. Note: {note}':
        'داواکاریی مۆڵەتەکەت بۆ {date} {status}. تێبینی: {note}',
    'Leave Requests': 'داواکارییەکانی مۆڵەت',
    'Pending': 'چاوەڕوان',
    'Reviewed': 'پشکنراو',
    'New Request': 'داواکاریی نوێ',
    'No leave requests found': 'هیچ داواکارییەکی مۆڵەت نەدۆزرایەوە',
    'Review: {name}': 'پشکنین: {name}',
    'Reason': 'هۆکار',
    'Decision': 'بڕیار',
    'Approve': 'پەسەندکردن',
    'Reject': 'ڕەتکردنەوە',
    'Note (optional)': 'تێبینی (ئیختیاری)',
    'Write an optional note...': 'تێبینییەکی ئیختیاری بنووسە...',
    'Submit': 'ناردن',
    'Leave request submitted!': 'داواکاریی مۆڵەت نێردرا!',
    'Failed to submit': 'ناردن سەرکەوتوو نەبوو',
    'Reviewed by': 'پشکنراوە لەلایەن',
    'on': 'لە',
    'Register': 'تۆماربوون',
    'Create your account': 'هەژمارەکەت دروست بکە',
    'Create Account': 'دروستکردنی هەژمار',
    'Already have an account?': 'پێشتر هەژمارت هەیە؟',
    'Login': 'چوونەژوورەوە',
    'Room Scanner': 'پشکنەری ژوور',
    'Scan room for faces': 'ژوور بپشکنە بۆ ڕووەکان',
    'Start Scan': 'دەستپێکردنی پشکنین',
    'Scanning Room...': 'ژوور پشکنین دەکرێت...',
    'Detected Faces': 'ڕووە دۆزراوەکان',
    'Recognized Students': 'خوێندکارە ناسراوەکان',
    'Unknown Faces': 'ڕووە نەناسراوەکان',
    'Admin Dashboard': 'داشبۆردی بەڕێوەبەر',
    'Total Users': 'کۆی بەکارهێنەران',
    'Present Today': 'ئامادەکانی ئەمڕۆ',
    'Late Today': 'دواکەوتووەکانی ئەمڕۆ',
    'Absent Today': 'غایبەکانی ئەمڕۆ',
    'Active Users': 'بەکارهێنەرە چالاکەکان',
    'Faces Registered': 'ڕووە تۆمارکراوەکان',
    'Manage Users': 'بەڕێوەبردنی بەکارهێنەران',
    'Manage Classes': 'بەڕێوەبردنی پۆلەکان',
    'Reports': 'ڕاپۆرتەکان',
    'All Attendance': 'هەموو ئامادەبوونەکان',
    "Today's Attendance": 'ئامادەبوونی ئەمڕۆ',
    'View All': 'بینیی هەموو',
    'No attendance records today': 'ئەمڕۆ هیچ تۆمارێکی ئامادەبوون نییە',
    'Export CSV': 'هەناردەکردنی CSV',
    'Clear filters': 'سڕینەوەی پالێوەرەکان',
    'Preparing CSV report...': 'ڕاپۆرتی CSV ئامادە دەکرێت...',
    'Update Status': 'نوێکردنەوەی دۆخ',
    'Reports Overview': 'پوختەی ڕاپۆرتەکان',
    'Generate attendance reports and exports':
        'ڕاپۆرت و هەناردەکانی ئامادەبوون دروست بکە',
    'Class Management': 'بەڕێوەبردنی پۆلەکان',
    'Create First Class': 'یەکەم پۆل دروست بکە',
    'Import Classes': 'هاوردەکردنی پۆلەکان',
    'Create Class': 'دروستکردنی پۆل',
    'Edit Class': 'دەستکاریکردنی پۆل',
    'Delete Class': 'سڕینەوەی پۆل',
    'Create': 'دروستکردن',
    'Delete': 'سڕینەوە',
    'Close': 'داخستن',
    'Import Complete': 'هاوردەکردن تەواو بوو',
    'Add Class': 'زیادکردنی پۆل',
    'Export Class': 'هەناردەکردنی پۆل',
    'Selected file could not be read.':
        'ناتوانرێت پەڕگەی هەڵبژێردراو بخوێندرێتەوە.',
    'Class import failed.': 'هاوردەکردنی پۆل سەرکەوتوو نەبوو.',
    'Class exported to {path}': 'پۆل هەنێردرا بۆ {path}',
    'Import Students CSV': 'هاوردەکردنی CSVی خوێندکاران',
    'Student list saved to {path}': 'لیستی خوێندکاران پاشەکەوت کرا بۆ {path}',
    'Class attendance saved to {path}':
        'ئامادەبوونی پۆل پاشەکەوت کرا بۆ {path}',
    'Add Student': 'زیادکردنی خوێندکار',
    'Edit Student': 'دەستکاریکردنی خوێندکار',
    'Delete Student': 'سڕینەوەی خوێندکار',
    'Save': 'پاشەکەوتکردن',
    'Student import failed.': 'هاوردەکردنی خوێندکار سەرکەوتوو نەبوو.',
    'Students': 'خوێندکاران',
    'Export Student List': 'هەناردەکردنی لیستی خوێندکاران',
    'Export Attendance CSV': 'هەناردەکردنی CSVی ئامادەبوون',
    'View Class Attendance': 'بینینی ئامادەبوونی پۆل',
    'Import CSV': 'هاوردەکردنی CSV',
    'Add First Student': 'یەکەم خوێندکار زیاد بکە',
    'Cancel Registration?': 'تۆمارکردن هەڵبوەشێنرێتەوە؟',
    'No': 'نەخێر',
    'Yes, Cancel': 'بەڵێ، هەڵبوەشێنەوە',
    'Registration Complete!': 'تۆمارکردن تەواو بوو!',
    'Student Registered!': 'خوێندکار تۆمار کرا!',
    'Done': 'تەواو',
    'Add Another': 'یەکێکی تر زیاد بکە',
    'Select Date': 'هەڵبژاردنی بەروار',
    'Export Attendance': 'هەناردەکردنی ئامادەبوون',
    'Mark All Present': 'هەموو وەک ئامادە نیشان بدە',
    'Save Roll Call': 'پاشەکەوتکردنی لیستی ناوەکان',
    'Roll call saved for {date}': 'لیستی ناوەکان بۆ {date} پاشەکەوت کرا',
    'Half Day': 'نیوەڕۆژ',
    '{name} Attendance': 'ئامادەبوونی {name}',
    '{name} Students': 'خوێندکارانی {name}',
    'Account Info (Read-only)': 'زانیاریی هەژمار (تەنها بۆ خوێندنەوە)',
    'Account Status': 'دۆخی هەژمار',
    'Active': 'چالاک',
    'All required images captured! Enter name and click Submit.':
        'هەموو وێنە پێویستەکان گیرا! ناو بنووسە و بنێرە.',
    'All 5 images captured! Enter name and click Submit.':
        'هەموو ٥ وێنەکە گیرا! ناو بنووسە و بنێرە.',
    'All notifications marked as read':
        'هەموو ئاگادارکردنەوەکان وەک خوێندراوە نیشان دران',
    'Already captured 5 images for this student':
        'بۆ ئەم خوێندکارە پێشتر ٥ وێنە گیراوە',
    'Already captured the required images for this student':
        'وێنە پێویستەکان بۆ ئەم خوێندکارە پێشتر گیراون',
    'Are you sure you want to delete {name}?':
        'دڵنیایت دەتەوێت {name} بسڕیتەوە؟',
    'Attendance Calendar': 'ڕۆژژمێری ئامادەبوون',
    'Attendance exported to {path}': 'ئامادەبوون هەنێردرا بۆ {path}',
    'Attendance Status': 'دۆخی ئامادەبوون',
    'Camera not available': 'کامێرا بەردەست نییە',
    'Cancel': 'هەڵوەشاندنەوە',
    'Captured Images': 'وێنە گیراوەکان',
    'Change Class': 'گۆڕینی پۆل',
    'Change Password': 'گۆڕینی وشەی نهێنی',
    'Check-In Recorded': 'هاتنەژوور تۆمار کرا',
    'Choose a class before starting Room Scanner':
        'پێش دەستپێکردنی پشکنەری ژوور پۆلێک هەڵبژێرە',
    'Class created successfully': 'پۆل بە سەرکەوتوویی دروست کرا',
    'Class deleted successfully': 'پۆل بە سەرکەوتوویی سڕایەوە',
    'Class Name': 'ناوی پۆل',
    'Class not created. Please restart registration.':
        'پۆل دروست نەکرا. تکایە تۆمارکردن دووبارە دەست پێ بکە.',
    'Class Setup': 'ڕێکخستنی پۆل',
    'Class updated successfully': 'پۆل بە سەرکەوتوویی نوێکرایەوە',
    'Class: {name}': 'پۆل: {name}',
    'Copy token': 'کۆپی کردنی تۆکن',
    'Create a new class and specify the number of students to register':
        'پۆلێکی نوێ دروست بکە و ژمارەی خوێندکارانی تۆمارکردن دیاری بکە',
    'Delete User': 'سڕینەوەی بەکارهێنەر',
    'Details': 'وردەکاری',
    'Disabled': 'ناچالاک',
    'Discard Changes': 'فڕێدانی گۆڕانکارییەکان',
    'e.g. Algorithms': 'وەک: ئەلگۆریتمەکان',
    'e.g. CS 101 - Section A': 'وەک: CS 101 - بەشی A',
    'e.g. Lab 3': 'وەک: تاقیگەی ٣',
    'e.g., 30, 50, 100': 'وەک: 30، 50، 100',
    'e.g., Class 10A, Computer Science 101':
        'وەک: پۆلی 10A، زانستی کۆمپیوتەر 101',
    'Email': 'ئیمەیڵ',
    'Email is required': 'ئیمەیڵ پێویستە',
    'End Time': 'کاتی کۆتایی',
    'Enter a valid email': 'ئیمەیڵێکی دروست بنووسە',
    'Enter full name': 'ناوی تەواو بنووسە',
    'Enter your reset token and choose a new password.':
        'تۆکنی نوێکردنەوە بنووسە و وشەی نهێنییەکی نوێ هەڵبژێرە.',
    'Error during scan: {error}': 'هەڵە لە کاتی پشکنین: {error}',
    'Error: {message}': 'هەڵە: {message}',
    'Explain the reason for your leave...': 'هۆکاری مۆڵەتەکەت ڕوون بکەرەوە...',
    'Export': 'هەناردەکردن',
    'Face Recognition': 'ناسینەوەی ڕوو',
    'Face Registered': 'ڕوو تۆمارکراوە',
    'Face registered': 'ڕوو تۆمارکراوە',
    'Failed': 'سەرکەوتوو نەبوو',
    'Failed to capture image': 'گرتنی وێنە سەرکەوتوو نەبوو',
    'Failed to capture image: {error}': 'گرتنی وێنە سەرکەوتوو نەبوو: {error}',
    'Failed to create class': 'دروستکردنی پۆل سەرکەوتوو نەبوو',
    'Failed to delete class': 'سڕینەوەی پۆل سەرکەوتوو نەبوو',
    'Failed to delete student': 'سڕینەوەی خوێندکار سەرکەوتوو نەبوو',
    'Failed to export absent list: {error}':
        'هەناردەکردنی لیستی غایبان سەرکەوتوو نەبوو: {error}',
    'Failed to export attendance': 'هەناردەکردنی ئامادەبوون سەرکەوتوو نەبوو',
    'Failed to export attendance report':
        'هەناردەکردنی ڕاپۆرتی ئامادەبوون سەرکەوتوو نەبوو',
    'Failed to export class attendance.':
        'هەناردەکردنی ئامادەبوونی پۆل سەرکەوتوو نەبوو.',
    'Failed to export class.': 'هەناردەکردنی پۆل سەرکەوتوو نەبوو.',
    'Failed to export students.': 'هەناردەکردنی خوێندکاران سەرکەوتوو نەبوو.',
    'Failed to generate report: {error}':
        'دروستکردنی ڕاپۆرت سەرکەوتوو نەبوو: {error}',
    'Failed to initialize camera: {error}':
        'ئامادەکردنی کامێرا سەرکەوتوو نەبوو: {error}',
    'Failed to mark attendance': 'تۆمارکردنی ئامادەبوون سەرکەوتوو نەبوو',
    'Failed to register face': 'تۆمارکردنی ڕوو سەرکەوتوو نەبوو',
    'Failed to reset password': 'نوێکردنەوەی وشەی نهێنی سەرکەوتوو نەبوو',
    'Failed to save captured image':
        'پاشەکەوتکردنی وێنەی گیراو سەرکەوتوو نەبوو',
    'Failed to save image': 'پاشەکەوتکردنی وێنە سەرکەوتوو نەبوو',
    'Failed to save roll call': 'پاشەکەوتکردنی لیستی ناوەکان سەرکەوتوو نەبوو',
    'Failed to save room scan photo':
        'پاشەکەوتکردنی وێنەی پشکنینی ژوور سەرکەوتوو نەبوو',
    'Failed to save settings': 'پاشەکەوتکردنی ڕێکخستنەکان سەرکەوتوو نەبوو',
    'Failed to update class': 'نوێکردنەوەی پۆل سەرکەوتوو نەبوو',
    'Failed to update status': 'نوێکردنەوەی دۆخ سەرکەوتوو نەبوو',
    'Failed to update student': 'نوێکردنەوەی خوێندکار سەرکەوتوو نەبوو',
    'Go to today': 'چوون بۆ ئەمڕۆ',
    'If that email exists, a reset token has been sent.':
        'ئەگەر ئەو ئیمەیڵە هەبوو، تۆکنی نوێکردنەوە نێردرا.',
    'Imported: {count}': 'هاوردەکراو: {count}',
    'Just now': 'ئێستا',
    '{count}m ago': '{count} خولەک پێش ئێستا',
    '{count}h ago': '{count} کاتژمێر پێش ئێستا',
    '{count}d ago': '{count} ڕۆژ پێش ئێستا',
    'Leave Date': 'بەرواری مۆڵەت',
    'Submitted {date} at {time}': 'نێردراوە لە {date} کاتژمێر {time}',
    'Manual Entry': 'تۆمارکردنی دەستی',
    'Maximum 200 students per batch': 'زۆرترین ٢٠٠ خوێندکار بۆ هەر کۆمەڵە',
    'Meeting Days': 'ڕۆژانی کۆبوونەوە',
    'Min 6 characters': 'کەمترین ٦ پیت',
    'N/A': 'بەردەست نییە',
    'Name cannot be empty': 'ناو نابێت بەتاڵ بێت',
    'Name is required': 'ناو پێویستە',
    'Name must be at least 2 characters': 'ناو دەبێت لانیکەم ٢ پیت بێت',
    'No absent attendees to export.': 'هیچ ئامادەنەبوویەک نییە بۆ هەناردەکردن.',
    'No attendance on weekends': 'لە ڕۆژانی پشوودا ئامادەبوون نییە',
    'No attendance record': 'هیچ تۆمارێکی ئامادەبوون نییە',
    'No attendance records found': 'هیچ تۆمارێکی ئامادەبوون نەدۆزرایەوە',
    'No cameras found': 'هیچ کامێرایەک نەدۆزرایەوە',
    'No classes found': 'هیچ پۆلێک نەدۆزرایەوە',
    'No classes found. Create a class first in Batch Register.':
        'هیچ پۆلێک نەدۆزرایەوە. سەرەتا لە تۆمارکردنی کۆمەڵەیی پۆلێک دروست بکە.',
    'No Face Data': 'هیچ داتایەکی ڕوو نییە',
    'No face data': 'هیچ داتایەکی ڕوو نییە',
    'No faces in this photo match any students in the selected class.':
        'هیچ ڕووێک لەم وێنەیەدا لەگەڵ هیچ خوێندکارێکی پۆلی هەڵبژێردراو ناگونجێت.',
    'No students found for this class.':
        'هیچ خوێندکارێک بۆ ئەم پۆلە نەدۆزرایەوە.',
    'No Students Recognized': 'هیچ خوێندکارێک نەناسرا',
    'No students registered in this class':
        'هیچ خوێندکارێک لەم پۆلەدا تۆمار نەکراوە',
    'No unread notifications': 'هیچ ئاگادارکردنەوەی نەخوێندراوە نییە',
    'No users found': 'هیچ بەکارهێنەرێک نەدۆزرایەوە',
    'No users match your search': 'هیچ بەکارهێنەرێک لەگەڵ گەڕانەکەت ناگونجێت',
    'Not logged in': 'نەچوویتە ژوورەوە',
    'Not provided': 'نەدراوە',
    'Notification removed': 'ئاگادارکردنەوە سڕایەوە',
    'Notifications about attendance, leaves, and system events will appear here.':
        'ئاگادارکردنەوەکانی ئامادەبوون، مۆڵەت و ڕووداوەکانی سیستەم لێرە دەر دەکەون.',
    'Number of Students': 'ژمارەی خوێندکاران',
    'Open Batch Register': 'کردنەوەی تۆمارکردنی کۆمەڵەیی',
    'Password is required': 'وشەی نهێنی پێویستە',
    'Password must be at least 6 characters':
        'وشەی نهێنی دەبێت لانیکەم ٦ پیت بێت',
    'Password reset successfully! Please log in.':
        'وشەی نهێنی بە سەرکەوتوویی نوێکرایەوە! تکایە بچۆ ژوورەوە.',
    'Password Tips': 'ئامۆژگارییەکانی وشەی نهێنی',
    "Passwords don't match": 'وشەکانی نهێنی یەک ناگرن',
    'Paste your reset token here': 'تۆکنی نوێکردنەوەکەت لێرە دابنێ',
    'Personal Information': 'زانیاریی کەسی',
    'Photo Capture Tips': 'ئامۆژگاریی گرتنی وێنە',
    'Image {current}/{total} captured': 'وێنەی {current}/{total} گیرا',
    'Capture Image ({current}/{total})': 'وێنە بگرە ({current}/{total})',
    'Please capture all 5 images before submitting':
        'تکایە پێش ناردن هەموو ٥ وێنەکە بگرە',
    'Please capture all required images before submitting':
        'تکایە پێش ناردن هەموو وێنە پێویستەکان بگرە',
    'Please capture at least {count} images': 'تکایە لانیکەم {count} وێنە بگرە',
    'Please upload at least {count} face images':
        'تکایە لانیکەم {count} وێنەی ڕوو باربکە',
    'Please confirm': 'تکایە پشتڕاست بکە',
    'Please confirm your password': 'تکایە وشەی نهێنییەکەت پشتڕاست بکە',
    'Please enter a class name': 'تکایە ناوی پۆل بنووسە',
    'Please enter a valid email address':
        'تکایە ناونیشانی ئیمەیڵێکی دروست بنووسە',
    'Please enter a valid number of students (1-200)':
        'تکایە ژمارەیەکی دروستی خوێندکاران بنووسە (1-200)',
    'Please enter a valid phone number': 'تکایە ژمارەیەکی دروستی مۆبایل بنووسە',
    'Please enter student name': 'تکایە ناوی خوێندکار بنووسە',
    'Please enter the reset token': 'تکایە تۆکنی نوێکردنەوە بنووسە',
    'Please enter your email address': 'تکایە ناونیشانی ئیمەیڵەکەت بنووسە',
    'Please provide a reason (min 5 characters)':
        'تکایە هۆکارێک بنووسە (لانیکەم ٥ پیت)',
    'Position your face within the circle and capture':
        'ڕووت لە ناو بازنەکەدا ڕێکبخە و وێنە بگرە',
    'Capture {count} images of your face from different angles':
        '{count} وێنە لە گۆشەی جیاوازەوە لە ڕووت بگرە',
    'Capture {count} photos from slightly different angles':
        '{count} وێنە لە ڕووکاری جیاوازەوە بگرە',
    'Maximum {count} images allowed': 'زۆرترین {count} وێنە ڕێپێدراوە',
    'Progress will be lost. Are you sure?':
        'هەموو پێشکەوتنەکە لەدەست دەچێت. دڵنیایت؟',
    'QR Code': 'کۆدی QR',
    'Quick Actions': 'کردارە خێراکان',
    'Quick Reports': 'ڕاپۆرتە خێراکان',
    'Recorded as Late': 'وەک دواکەوتوو تۆمار کرا',
    'Refresh': 'نوێکردنەوە',
    'Register Students': 'تۆمارکردنی خوێندکاران',
    'Register your face': 'ڕووت تۆمار بکە',
    'Registration failed': 'تۆمارکردن سەرکەوتوو نەبوو',
    'Report saved: {fileName}': 'ڕاپۆرت پاشەکەوت کرا: {fileName}',
    'Reset Token': 'تۆکنی نوێکردنەوە',
    'Reset token generated. It has been pre-filled below.':
        'تۆکنی نوێکردنەوە دروست کرا. خوارەوە پێشتر پڕکراوەتەوە.',
    'Reset Your Password': 'وشەی نهێنیی خۆت نوێ بکەرەوە',
    'Review Request': 'پشکنینی داواکاری',
    'Role': 'ڕۆڵ',
    'Room': 'ژوور',
    'Room Scan': 'پشکنینی ژوور',
    'Room Scanner - {name}': 'پشکنەری ژوور - {name}',
    'Scan Room': 'پشکنینی ژوور',
    'Search users...': 'گەڕان بەدوای بەکارهێنەراندا...',
    'Select Class': 'هەڵبژاردنی پۆل',
    'Select Date Range': 'هەڵبژاردنی مەودای بەروار',
    'Select Report Type': 'هەڵبژاردنی جۆری ڕاپۆرت',
    'Set New Password': 'وشەی نهێنیی نوێ دابنێ',
    'Set up your teacher profile': 'هەژمارەکەت ڕێکبخە',
    'Settings saved successfully': 'ڕێکخستنەکان بە سەرکەوتوویی پاشەکەوت کران',
    'Show All': 'هەموو نیشان بدە',
    'Show Unread Only': 'تەنها نەخوێندراوەکان نیشان بدە',
    'Sign In': 'چوونەژوورەوە',
    'Skipped: {count}': 'بازدراو: {count}',
    'Start taking attendance': 'دەست بە تۆمارکردنی ئامادەبوون بکە',
    'Start Time': 'کاتی دەستپێک',
    'Status updated successfully': 'دۆخ بە سەرکەوتوویی نوێکرایەوە',
    'Student deleted successfully': 'خوێندکار بە سەرکەوتوویی سڕایەوە',
    'Student ID: {id}': 'ناسنامەی خوێندکار: {id}',
    'Student Name': 'ناوی خوێندکار',
    'Student updated successfully': 'خوێندکار بە سەرکەوتوویی نوێکرایەوە',
    'Subject': 'بابەت',
    'Submit Leave Request': 'ناردنی داواکاریی مۆڵەت',
    'Take Attendance': 'تۆمارکردنی ئامادەبوون',
    'Take one photo to detect all faces in the selected class.':
        'یەک وێنە بگرە بۆ دۆزینەوەی هەموو ڕووەکان لە پۆلی هەڵبژێردراو.',
    'Token copied': 'تۆکن کۆپی کرا',
    'Token pre-filled from backend response':
        'تۆکن لە وەڵامی باکئەندەوە پێشتر پڕکراوەتەوە',
    'Undo': 'گەڕانەوە',
    'User': 'بەکارهێنەر',
    'User deleted': 'بەکارهێنەر سڕایەوە',
    'View Details': 'بینیینی وردەکاری',
    'Weekend': 'پشووی هەفتانە',
    'Welcome, {name}!': 'بەخێربێیت، {name}!',
    'Yes': 'بەڵێ',
    'Check In': 'چوونەژوورەوە',
    'Duration': 'ماوە',
    'Method': 'شێواز',
    'Notes': 'تێبینی',
    'Total': 'کۆی',
    'Optional': 'ئاریشەیی',
    'START REGISTRATION': 'دەستپێکردنی تۆمارکردن',
    'At least 8 characters long': 'لانیکەم ٨ پیت بێت',
    'Mix uppercase and lowercase letters': 'پیتی گەورە و بچووک تێکەڵ بکە',
    'Include numbers and symbols': 'ژمارە و هێما تێدایە',
    'Avoid using personal information':
        'لە بەکارهێنانی زانیاریی کەسی خۆت بپارێزە',
    'Create a password': 'وشەی نهێنی دروست بکە',
    'Confirm Password': 'پشتڕاستکردنەوەی وشەی نهێنی',
    'Confirm your password': 'وشەی نهێنییەکەت پشتڕاست بکەرەوە',
    'Retake': 'دووبارە وێنە بگرە',
    'Confirm': 'پشتڕاستکردنەوە',
    'Submit & Next Student': 'بنێرە و بچۆ بۆ خوێندکارێکی داهاتوو',
    'Submit & Finish': 'بنێرە و تەواو بکە',
    'Set up your account': 'هەژمارەکەت ڕێکبخە',
    'Enter your registered email': 'ئیمەیڵی تۆمارکراوت بنووسە',
    'Get Reset Token': 'وەرگرتنی تۆکنی نوێکردنەوە',
    'Generate Report': 'دروستکردنی ڕاپۆرت',
    'Attendance Summary': 'پوختەی ئامادەبوون',
    'Overview of attendance statistics':
        'تێڕوانینێکی گشتی بۆ ئامارەکانی ئامادەبوون',
    'Detailed Report': 'ڕاپۆرتی ورد',
    'Complete attendance records with timestamps':
        'تۆمارە تەواوەکانی ئامادەبوون لەگەڵ کات',
    'Absent Report': 'ڕاپۆرتی غیاب',
    'Start Date': 'بەرواری دەستپێک',
    'End Date': 'بەرواری کۆتایی',
    'Today': 'ئەمڕۆ',
    'This Week': 'ئەم هەفتەیە',
    'This Month': 'ئەم مانگە',
    'List of absent attendees': 'لیستی ئەو کەسانەی ئامادە نەبوون',
    'START ROOM SCAN': 'دەستپێکردنی پشکنینی ژوور',
    'EXPORT ABSENT': 'دەرخستنی غایبەکان',
    'DONE': 'تەواو',
    'RETRY SCAN': 'دووبارە پشکنین بکە',
    'Missing Attendees': 'غایبەکان',
    'Present Attendees': 'ئامادەبووەکان',
    'Missing': 'غایب',
    'Create your account and start managing attendance effortlessly.':
        'هەژمارەکەت دروست بکە و بە ئاسانی دەست بە بەڕێوەبردنی ئامادەبوون بکە.',
  };

  static const Map<String, Map<String, String>> translations = {
    englishCode: {
      'appTitle': 'Face Attendance System',
      'language': 'Language',
      'languageEnglish': 'English',
      'languageSorani': 'Sorani Kurdish',
      'splashTagline': 'Quick  •  Secure  •  Automated',
      'welcomeBack': 'Welcome back',
      'signInTeacherDashboard': 'Sign in to your dashboard',
      'email': 'Email',
      'enterEmail': 'Enter your email',
      'emailRequired': 'Email is required',
      'enterValidEmail': 'Enter a valid email',
      'password': 'Password',
      'enterPassword': 'Enter your password',
      'passwordRequired': 'Password is required',
      'passwordMinLength': 'Password must be at least 6 characters',
      'rememberMe': 'Remember me',
      'forgotPassword': 'Forgot Password?',
      'forgotPasswordTitle': 'Forgot Password',
      'forgotPasswordHelp':
          'Enter your email address and we\'ll send you a link to reset your password.',
      'pleaseEnterEmail': 'Please enter your email',
      'pleaseEnterValidEmail': 'Please enter a valid email',
      'cancel': 'Cancel',
      'sendResetLink': 'Send Reset Link',
      'passwordResetSent': 'Password reset link sent to your email',
      'failedToSendResetLink': 'Failed to send reset link',
      'loginFailed': 'Login failed',
      'signIn': 'Sign In',
      'dontHaveAccount': "Don't have an account?",
      'signUp': 'Sign Up',
      'teacherAttendanceSystem': 'Attendance System',
      'smartRoomScanning': 'Smart Room Scanning',
      'processEntireHallsSeconds': 'Process entire halls in seconds',
      'faceRecognition': 'Face Recognition',
      'automatedStudentIdentification': 'Automated student identification',
      'analyticsDashboard': 'Analytics Dashboard',
      'trackAttendanceTrends': 'Track attendance trends',
      'dashboard': 'Dashboard',
      'history': 'History',
      'profile': 'Profile',
      'roomScanner': 'Room Scanner',
      'batchRegister': 'Batch Register',
      'notifications': 'Notifications',
      'leaveRequests': 'Leave Requests',
      'management': 'MANAGEMENT',
      'editAttendance': 'Edit Attendance',
      'classes': 'Classes',
      'adminPanel': 'Admin Panel',
      'teacherPortal': 'Attendance Portal',
      'collapse': 'Collapse',
      'signOut': 'Sign out',
      'signOutTitle': 'Sign Out',
      'signOutConfirm': 'Are you sure you want to sign out?',
      'deleteAccountTitle': 'Delete Account',
      'deleteAccountConfirm':
          'Are you sure you want to permanently delete your account? This will remove your classes, students, attendance records, and notifications.',
      'deleteAccountWarning': 'This action cannot be undone.',
      'deleteAccountFailed': 'Failed to delete account',
      'user': 'User',
      'refresh': 'Refresh',
      'totalPresent': 'Total Present',
      'totalLate': 'Total Late',
      'totalAbsent': 'Total Absent',
      'attendanceRate': 'Attendance Rate',
      'quickActions': 'Quick Actions',
      'manageClasses': 'Manage Classes',
      'fullHistory': 'Full History',
      'todaysStatus': "Today's Status",
      'noAttendanceToday': 'No attendance recorded today',
      'goodMorning': 'Good morning',
      'goodAfternoon': 'Good afternoon',
      'goodEvening': 'Good evening',
      'teacher': 'User',
      'admin': 'Admin',
      'phone': 'Phone',
      'department': 'Department',
      'faceRegistered': 'Face Registered',
      'yes': 'Yes',
      'no': 'No',
      'account': 'Account',
      'manageProfileSettings': 'Manage your profile and settings',
      'actions': 'Actions',
      'editProfile': 'Edit Profile',
      'updateNamePhoneDepartment': 'Update your name, phone, and department',
      'changePassword': 'Change Password',
      'updateAccountPassword': 'Update your account password',
      'reregisterFace': 'Re-register Face',
      'updateFaceData': 'Update your facial recognition data',
      'viewAttendanceUpdates': 'View attendance and system updates',
      'submitOrReviewLeave': 'Submit or review leave requests',
      'adminDashboard': 'Admin Dashboard',
      'manageUsersReportsSettings': 'Manage users, reports, and settings',
      'session': 'Session',
      'notLoggedIn': 'Not logged in',
      'systemSettings': 'System Settings',
      'save': 'Save',
      'reloadFromServer': 'Reload from server',
      'unsavedChanges': 'You have unsaved changes',
      'appearance': 'Appearance',
      'backendConnection': 'Backend Connection',
      'apiBaseUrl': 'API Base URL',
      'test': 'Test',
      'apply': 'Apply',
      'connectedHealthy': 'Connected! Server is healthy.',
      'serverRespondedWithStatus': 'Server responded with status {code}',
      'failedToConnect': 'Failed to connect: {reason}',
      'urlResetDefault': 'URL reset to default',
      'resetToDefault': 'Reset to default URL',
      'attendanceTime': 'Attendance Time',
      'lateCheckInThreshold': 'Late Check-In Threshold',
      'studentsArrivingLate':
          'Students arriving after this time are marked late',
      'attendanceAlertThreshold': 'Attendance Alert Threshold',
      'notifyWhenAttendanceBelow': 'Notify when attendance falls below this %',
      'attendanceMethods': 'Attendance Methods',
      'allowAttendanceFace': 'Allow attendance via facial recognition',
      'qrCodeAttendance': 'QR Code Attendance',
      'allowAttendanceQr': 'Allow attendance via QR code scanning',
      'manualEntry': 'Manual Entry',
      'allowTeachersManual': 'Allow manual attendance entry',
      'faceRegistration': 'Face Registration',
      'minimumFaceImages': 'Minimum Face Images',
      'minimumPhotosRequired': 'Minimum photos required for face registration',
      'maximumFaceImages': 'Maximum Face Images',
      'maximumPhotosAllowed': 'Maximum photos allowed for registration',
      'qrSession': 'QR Session',
      'sessionDuration': 'Session Duration',
      'minutesActive': 'How many minutes a QR session stays active',
      'application': 'Application',
      'appName': 'App Name',
      'displayNameShown': 'Display name shown in the application',
      'saving': 'Saving...',
      'saveAllSettings': 'Save All Settings',
      'discardChanges': 'Discard Changes',
      'darkMode': 'Dark Mode',
      'lightMode': 'Light Mode',
      'toggleTheme': 'Toggle between dark and light theme',
      'backendUrlUpdated':
          'Backend URL updated. Restart the app to apply fully.',
    },
    soraniCode: {
      'appTitle': 'سیستەمی ئامادەبوونی ڕوو',
      'language': 'زمان',
      'languageEnglish': 'ئینگلیزی',
      'languageSorani': 'کوردی سۆرانی',
      'splashTagline': 'خێرا  •  پارێزراو  •  خۆکار',
      'welcomeBack': 'بەخێربێیتەوە',
      'signInTeacherDashboard': 'بچۆرە ژوورەوە بۆ داشبۆردەکەت',
      'email': 'ئیمەیڵ',
      'enterEmail': 'ئیمەیڵەکەت بنووسە',
      'emailRequired': 'ئیمەیڵ پێویستە',
      'enterValidEmail': 'ئیمەیڵێکی دروست بنووسە',
      'password': 'وشەی نهێنی',
      'enterPassword': 'وشەی نهێنییەکەت بنووسە',
      'passwordRequired': 'وشەی نهێنی پێویستە',
      'passwordMinLength': 'وشەی نهێنی دەبێت لانیکەم ٦ پیت بێت',
      'rememberMe': 'لەبیرم بێت',
      'forgotPassword': 'وشەی نهێنی لەبیرکردووە؟',
      'forgotPasswordTitle': 'وشەی نهێنی لەبیرکردووە',
      'forgotPasswordHelp':
          'ئیمەیڵەکەت بنووسە، بەستەرێک دەنێرین بۆ گۆڕینی وشەی نهێنی.',
      'pleaseEnterEmail': 'تکایە ئیمەیڵەکەت بنووسە',
      'pleaseEnterValidEmail': 'تکایە ئیمەیڵێکی دروست بنووسە',
      'cancel': 'هەڵوەشاندنەوە',
      'sendResetLink': 'ناردنی بەستەری نوێکردنەوە',
      'passwordResetSent':
          'بەستەری نوێکردنەوەی وشەی نهێنی بۆ ئیمەیڵەکەت نێردرا',
      'failedToSendResetLink': 'ناردنی بەستەری نوێکردنەوە سەرکەوتوو نەبوو',
      'loginFailed': 'چوونەژوورەوە سەرکەوتوو نەبوو',
      'signIn': 'چوونەژوورەوە',
      'dontHaveAccount': 'هەژمارەت نییە؟',
      'signUp': 'هەژمار دروست بکە',
      'teacherAttendanceSystem': 'سیستەمی ئامادەبوون',
      'smartRoomScanning': 'پشکنینی زیرەکی ژوور',
      'processEntireHallsSeconds':
          'هەموو هۆڵەکان لە چەند چرکەیەکدا پڕۆسێس دەکات',
      'faceRecognition': 'ناسینەوەی ڕوو',
      'automatedStudentIdentification': 'ناساندنی خۆکاری خوێندکار',
      'analyticsDashboard': 'داشبۆردی شیکاری',
      'trackAttendanceTrends': 'شوێنی ئاڕاستەکانی ئامادەبوون بگرە',
      'dashboard': 'داشبۆرد',
      'history': 'مێژوو',
      'profile': 'پرۆفایل',
      'roomScanner': 'پشکنەری ژوور',
      'batchRegister': 'تۆمارکردنی کۆمەڵەیی',
      'notifications': 'ئاگادارکردنەوەکان',
      'leaveRequests': 'داواکارییەکانی مۆڵەت',
      'management': 'بەڕێوەبەرایەتی',
      'editAttendance': 'دەستکاریکردنی ئامادەبوون',
      'classes': 'پۆلەکان',
      'adminPanel': 'پانێڵی بەڕێوەبەر',
      'teacherPortal': 'دەروازەی ئامادەبوون',
      'collapse': 'کورتکردنەوە',
      'signOut': 'چوونەدەرەوە',
      'signOutTitle': 'چوونەدەرەوە',
      'signOutConfirm': 'دڵنیایت دەتەوێت بچیتەدەرەوە؟',
      'deleteAccountTitle': 'سڕینەوەی هەژمار',
      'deleteAccountConfirm':
          'دڵنیایت دەتەوێت هەژمارەکەت بە تەواوی بسڕیتەوە؟ ئەمە پۆلەکان، خوێندکاران، تۆمارەکانی ئامادەبوون و ئاگادارکردنەوەکان دەسڕێتەوە.',
      'deleteAccountWarning': 'ئەم کردارە ناتوانرێت بگەڕێندرێتەوە.',
      'deleteAccountFailed': 'سڕینەوەی هەژمار سەرکەوتوو نەبوو',
      'user': 'بەکارهێنەر',
      'refresh': 'نوێکردنەوە',
      'totalPresent': 'کۆی ئامادەکان',
      'totalLate': 'کۆی دواکەوتووەکان',
      'totalAbsent': 'کۆی غایبەکان',
      'attendanceRate': 'ڕێژەی ئامادەبوون',
      'quickActions': 'کردارە خێراکان',
      'manageClasses': 'بەڕێوەبردنی پۆلەکان',
      'fullHistory': 'مێژووی تەواو',
      'todaysStatus': 'دۆخی ئەمڕۆ',
      'noAttendanceToday': 'ئەمڕۆ هیچ تۆمارێکی ئامادەبوون نییە',
      'goodMorning': 'بەیانی باش',
      'goodAfternoon': 'نیوەڕۆ باش',
      'goodEvening': 'ئێوارە باش',
      'teacher': 'بەکارهێنەر',
      'admin': 'بەڕێوەبەر',
      'phone': 'ژمارەی مۆبایل',
      'department': 'بەش',
      'faceRegistered': 'ڕوو تۆمارکراوە',
      'yes': 'بەڵێ',
      'no': 'نەخێر',
      'account': 'هەژمار',
      'manageProfileSettings': 'پرۆفایل و ڕێکخستنەکانت بەڕێوەببە',
      'actions': 'کردارەکان',
      'editProfile': 'دەستکاریکردنی پرۆفایل',
      'updateNamePhoneDepartment': 'ناو، ژمارەی مۆبایل و بەشەکەت نوێ بکەرەوە',
      'changePassword': 'گۆڕینی وشەی نهێنی',
      'updateAccountPassword': 'وشەی نهێنیی هەژمارەکەت نوێ بکەرەوە',
      'reregisterFace': 'دووبارە تۆمارکردنی ڕوو',
      'updateFaceData': 'داتاکانی ناسینەوەی ڕوو نوێ بکەرەوە',
      'viewAttendanceUpdates': 'ئاگادارکردنەوەکانی ئامادەبوون و سیستەم ببینە',
      'submitOrReviewLeave': 'داواکارییەکانی مۆڵەت بنێرە یان پشکنەوە',
      'adminDashboard': 'داشبۆردی بەڕێوەبەر',
      'manageUsersReportsSettings':
          'بەکارهێنەران، ڕاپۆرتەکان و ڕێکخستنەکان بەڕێوەببە',
      'session': 'دانیشتن',
      'notLoggedIn': 'نەچوویتە ژوورەوە',
      'systemSettings': 'ڕێکخستنەکانی سیستەم',
      'save': 'پاشەکەوتکردن',
      'reloadFromServer': 'دووبارە هێنان لە سێرڤەر',
      'unsavedChanges': 'گۆڕانکارییە پاشەکەوت نەکراوەکانت هەن',
      'appearance': 'دەرکەوتن',
      'backendConnection': 'پەیوەندی باکئێند',
      'apiBaseUrl': 'ناونیشانی بنەڕەتی API',
      'test': 'تاقیکردنەوە',
      'apply': 'جێبەجێکردن',
      'connectedHealthy': 'پەیوەست بوو! سێرڤەر تەندروستە.',
      'serverRespondedWithStatus': 'سێرڤەر بە دۆخی {code} وەڵامی دا',
      'failedToConnect': 'پەیوەست بوون سەرکەوتوو نەبوو: {reason}',
      'urlResetDefault': 'URL بۆ بنەڕەت گەڕایەوە',
      'resetToDefault': 'گەڕاندنەوە بۆ URL ی بنەڕەت',
      'attendanceTime': 'کاتی ئامادەبوون',
      'lateCheckInThreshold': 'سنووری دواکەوتنی هاتنەژوور',
      'studentsArrivingLate':
          'خوێندکارانی دواتر لەو کاتە دواکەوتوو تۆمار دەکرێن',
      'attendanceAlertThreshold': 'سنووری ئاگادارکردنەوەی ئامادەبوون',
      'notifyWhenAttendanceBelow':
          'ئاگاداربکەوە کاتێک ئامادەبوون لە ژێر ئەم ڕێژەیە دابەزێت',
      'attendanceMethods': 'شێوازەکانی ئامادەبوون',
      'allowAttendanceFace': 'ڕێگە بدە بە ئامادەبوون بە ناسینەوەی ڕوو',
      'qrCodeAttendance': 'ئامادەبوونی کۆدی QR',
      'allowAttendanceQr': 'ڕێگە بدە بە ئامادەبوون بە پشکنینی کۆدی QR',
      'manualEntry': 'تۆمارکردنی دەستی',
      'allowTeachersManual': 'ڕێگە بدە بە تۆمارکردنی دەستی ئامادەبوون',
      'faceRegistration': 'تۆمارکردنی ڕوو',
      'minimumFaceImages': 'کەمترین وێنەی ڕوو',
      'minimumPhotosRequired': 'کەمترین ژمارەی وێنەی پێویست بۆ تۆمارکردنی ڕوو',
      'maximumFaceImages': 'زۆرترین وێنەی ڕوو',
      'maximumPhotosAllowed': 'زۆرترین ژمارەی وێنەی ڕێگەپێدراو بۆ تۆمارکردن',
      'qrSession': 'دانیشتنی QR',
      'sessionDuration': 'ماوەی دانیشتن',
      'minutesActive': 'دانیشتنی QR چەند خولەک چالاک دەمێنێت',
      'application': 'بەرنامە',
      'appName': 'ناوی بەرنامە',
      'displayNameShown': 'ناوی پیشاندراوی ناو بەرنامە',
      'saving': 'پاشەکەوت دەکرێت...',
      'saveAllSettings': 'پاشەکەوتکردنی هەموو ڕێکخستنەکان',
      'discardChanges': 'فڕێدانی گۆڕانکارییەکان',
      'darkMode': 'دۆخی تاریک',
      'lightMode': 'دۆخی ڕووناک',
      'toggleTheme': 'گۆڕین لە نێوان ڕووکارە تاریک و ڕووناک',
      'backendUrlUpdated':
          'URLی باکئێند نوێکرایەوە. بەرنامەکە دووبارە دەستپێبکە بۆ جێبەجێکردنی تەواو.',
    },
  };
}
