class ArabicLocalization {
  static const Map<String, String> phrases = {
    'Supervisor Dashboard': 'لوحة متابعة المشرف',
    'Manual Refresh': 'تحديث يدوي',
    'Attendance Reports': 'تقارير الحضور',
    'Export Center': 'مركز التصدير',
    'No dashboard data available.': 'لا توجد بيانات متاحة للوحة المتابعة.',
    'Facial Recognition Operations': 'عمليات التعرف على الوجه',
    'Monitor detection quality, room activity, attendance reliability, and flagged behavior across lecture halls.':
        'راقب جودة التعرف، ونشاط القاعات، وموثوقية الحضور، والسلوكيات التي تحتاج إلى متابعة عبر القاعات الدراسية.',
    'Review Attendance': 'مراجعة الحضور',
    'Export Attendance': 'تصدير الحضور',
    'Investigate Flags': 'التحقيق في التنبيهات',
    'Clear filters': 'مسح عوامل التصفية',
    'Live mode': 'الوضع المباشر',
    'Auto refresh room telemetry': 'تحديث تلقائي لبيانات القاعات',
    'Available only for today': 'متاح لليوم الحالي فقط',
    'Class Management': 'إدارة الصفوف',
    'Create First Class': 'إنشاء أول صف',
    'Import Classes': 'استيراد الصفوف',
    'Export Class': 'تصدير الصف',
    'Edit Class': 'تعديل الصف',
    'Delete Class': 'حذف الصف',
    'Class Name': 'اسم الصف',
    'e.g. CS 101 - Section A': 'مثال: CS 101 - الشعبة A',
    'Subject': 'المادة',
    'e.g. Algorithms': 'مثال: الخوارزميات',
    'Room': 'القاعة',
    'e.g. Lab 3': 'مثال: مختبر 3',
    'Start Time': 'وقت البدء',
    'End Time': 'وقت الانتهاء',
    'Meeting Days': 'أيام الاجتماع',
    'Create Class': 'إنشاء صف',
    'Create': 'إنشاء',
    'Save': 'حفظ',
    'Class created successfully': 'تم إنشاء الصف بنجاح',
    'Class updated successfully': 'تم تحديث الصف بنجاح',
    'Failed to create class': 'فشل إنشاء الصف',
    'Failed to update class': 'فشل تحديث الصف',
    'Delete "{name}" and all linked students? Existing attendance history will remain.':
        'هل تريد حذف "{name}" مع جميع الطلاب المرتبطين به؟ سيبقى سجل الحضور السابق محفوظاً.',
    'Delete': 'حذف',
    'Class deleted successfully': 'تم حذف الصف بنجاح',
    'Failed to delete class': 'فشل حذف الصف',
    'Selected file could not be read.': 'تعذر قراءة الملف المحدد.',
    'Class import failed.': 'فشل استيراد الصفوف.',
    'Import Complete': 'اكتمل الاستيراد',
    'Imported: {count}': 'تم استيراد: {count}',
    'Skipped: {count}': 'تم التخطي: {count}',
    'Details': 'التفاصيل',
    'Close': 'إغلاق',
    'No classes found': 'لم يتم العثور على صفوف',
    'Add Class': 'إضافة صف',
    '{count} students': '{count} طلاب',
    'Present': 'حاضر',
    'Late': 'متأخر',
    'Absent': 'غائب',
    'Status': 'الحالة',
    'Confidence': 'الثقة',
    'Sunday': 'الأحد',
    'Monday': 'الاثنين',
    'Tuesday': 'الثلاثاء',
    'Wednesday': 'الأربعاء',
    'Thursday': 'الخميس',
    'Friday': 'الجمعة',
    'Saturday': 'السبت',
    'All rooms': 'كل القاعات',
    'All classes': 'كل الصفوف',
    'Room not assigned': 'لم يتم تحديد القاعة',
    'Action Center': '???? ?????????',
    'Add Class To Group': '????? ?? ??? ????????',
    'Add Users By Email': '????? ?????????? ??? ?????? ??????????',
    'Admin Access Key': 'مفتاح وصول المسؤول',
    'Admin Sign In': 'تسجيل دخول المشرف',
    'Admin access key is required': 'مطلوب مفتاح وصول المسؤول',
    'Admin access required': 'مطلوب وصول المشرف',
    'Admin accounts are created by admins':
        'يتم إنشاء حسابات المشرف من قبل المسؤولين',
    'Admin sign-in requires an access key':
        'يتطلب تسجيل دخول المسؤول مفتاح وصول',
    'Sign in to your government account': 'سجّل الدخول إلى حسابك الحكومي',
    'Enter your government email and password to continue':
        'أدخل بريدك الإلكتروني الحكومي وكلمة المرور للمتابعة',
    'Continue to Sign In': 'المتابعة إلى تسجيل الدخول',
    'Government sign-in required': 'مطلوب تسجيل الدخول الحكومي',
    'Use your official government email and password to access the attendance system.':
        'استخدم بريدك الإلكتروني الحكومي الرسمي وكلمة المرور للوصول إلى نظام الحضور.',
    'Before you continue': 'قبل المتابعة',
    'Have your government email ready': 'جهّز بريدك الإلكتروني الحكومي',
    'Enter your password on the next screen':
        'أدخل كلمة المرور في الشاشة التالية',
    'Continue to the secure sign-in form': 'تابع إلى نموذج تسجيل الدخول الآمن',
    'Government Attendance Access': 'الوصول الحكومي إلى نظام الحضور',
    'Protected sign-in experience': 'تجربة تسجيل دخول محمية',
    'Review the access requirements before opening the sign-in form':
        'راجع متطلبات الوصول قبل فتح نموذج تسجيل الدخول.',
    'Government account access': 'الوصول إلى الحساب الحكومي',
    'Use the official credentials assigned to your organization':
        'استخدم بيانات الاعتماد الرسمية المخصصة لجهتك.',
    'Continue securely': 'تابع بأمان',
    'Move to the existing login page when you are ready to sign in':
        'انتقل إلى صفحة تسجيل الدخول الحالية عندما تكون جاهزاً لتسجيل الدخول.',
    'Alert': 'يُحذًِر',
    'All Classes': 'جميع الفصول',
    'All Dates': 'جميع التواريخ',
    'All notifications marked as read':
        'تم وضع علامة "مقروءة" على جميع الإشعارات',
    'Approved': 'موافقة',
    'Attendance': '??????',
    'Attendance History': 'تاريخ الحضور',
    'Attendance Status': 'حالة الحضور',
    'Back to Login': 'العودة إلى تسجيل الدخول',
    'Camera not available': 'الكاميرا غير متوفرة',
    'Checked in at {time}': 'تم تسجيل الوصول في {time}',
    'Class Data Exports': 'تصدير بيانات الفئة',
    'Confirm New Password': 'تأكيد كلمة المرور الجديدة',
    'Copy token': 'نسخ الرمز المميز',
    'Create a group and at least one class to start linking classes.':
        'أنشئ مجموعة وفصلًا واحدًا على الأقل لبدء ربط الفصول.',
    'Create a group first, then invite users by email and attach classes to it.':
        'أنشئ مجموعة أولاً، ثم قم بدعوة المستخدمين عبر البريد الإلكتروني وأرفق الفصول الدراسية بها.',
    'Create your first group': '???? ??????? ??????',
    'Dashboard unavailable': '???? ?????? ??? ?????',
    'Date': 'تاريخ',
    'Decision': 'قرار',
    'Enter new password (min 6 characters)':
        'أدخل كلمة المرور الجديدة (6 أحرف على الأقل)',
    'Enter the admin access key': 'أدخل مفتاح وصول المسؤول',
    'Enter the email address associated with your account. A password reset token will be generated.':
        'أدخل عنوان البريد الإلكتروني المرتبط بحسابك. سيتم إنشاء رمز إعادة تعيين كلمة المرور.',
    'Enter your registered email': 'أدخل بريدك الإلكتروني المسجل',
    'Enter your reset token and choose a new password.':
        'أدخل رمز إعادة التعيين الخاص بك واختر كلمة مرور جديدة.',
    'Existing admin accounts must enter the admin access key before the admin dashboard will open.':
        'يجب أن تقوم حسابات المسؤول الحالية بإدخال مفتاح وصول المسؤول قبل أن يتم فتح لوحة تحكم المسؤول.',
    'Explain the reason for your leave...': 'وضح سبب إجازتك...',
    'Export Attendance CSV': 'تصدير الحضور CSV',
    'Export Student List': 'تصدير قائمة الطلاب',
    'Export attendance records by date range and optional class filter.':
        'تصدير سجلات الحضور حسب النطاق الزمني ومرشح الفصل الاختياري.',
    'Export the selected class roster, attendance CSV, or a full class snapshot.':
        'قم بتصدير قائمة الفصل الدراسي المحدد أو ملف الحضور CSV أو لقطة الفصل الكامل.',
    'Face registered': 'تم تسجيل الوجه',
    'Face scan ready': '??? ????? ????',
    'Failed': 'فشل',
    'Failed to capture image': 'فشل التقاط الصورة',
    'Failed to mark attendance': 'فشل في تحديد الحضور',
    'Failed to save roll call': 'فشل حفظ المكالمة',
    'Failed to save settings': 'فشل في حفظ الإعدادات',
    'Failed to submit': 'فشل الإرسال',
    'Failed to update profile': 'فشل في تحديث الملف الشخصي',
    'Frame ID': 'معرف الإطار',
    'Full attendance records for this student across all available dates.':
        'سجلات الحضور الكاملة لهذا الطالب في جميع التواريخ المتاحة.',
    'Generate attendance reports and exports': 'إنشاء تقارير الحضور والصادرات',
    'Get Reset Token': 'احصل على رمز إعادة التعيين',
    'Group Workspace': '????? ??? ????????',
    'Groups Managed': '????????? ????????',
    'Half Day': 'نصف يوم',
    'In this local deployment, the reset token is returned directly and pre-filled for convenience. In production, it would be sent to your email.':
        'في هذا النشر المحلي، يتم إرجاع رمز إعادة التعيين مباشرة ويتم ملؤه مسبقًا لتسهيل الأمر. في الإنتاج، سيتم إرسالها إلى البريد الإلكتروني الخاص بك.',
    'Joined: {date}': 'انضم: {date}',
    'Last updated {time}': '??? ????? {time}',
    'Latency': 'كمون',
    'Launch batch registration, create groups, link classes, and invite users without leaving this dashboard.':
        'قم بتشغيل التسجيل المجمع، وإنشاء مجموعات، وربط الفئات، ودعوة المستخدمين دون مغادرة لوحة المعلومات هذه.',
    'Leave': '?????',
    'Leave Date': 'تاريخ المغادرة',
    'Leave request deleted': 'تم حذف طلب الإجازة',
    'Leave request submitted!': 'تم تقديم طلب الإجازة!',
    'Leave request {status}': 'ترك الطلب {status}',
    'Linked Account: {id}': 'الحساب المرتبط: {id}',
    'Liveness': 'حيوية',
    'Locking identity': '????? ??????',
    'Manage batch registration, user groups, linked classes, and email invites from one workspace.':
        'إدارة التسجيل المجمع ومجموعات المستخدمين والفصول المرتبطة ودعوات البريد الإلكتروني من مساحة عمل واحدة.',
    'Mark all as read': 'وضع علامة على الكل كمقروءة',
    'N/A': 'لا يوجد',
    'New Password': 'كلمة المرور الجديدة',
    'No Face Data': 'لا توجد بيانات الوجه',
    'No attendance records found': 'لم يتم العثور على سجلات الحضور',
    'No face data': 'لا توجد بيانات الوجه',
    'No leave requests found': 'لم يتم العثور على طلبات الإجازة',
    'No notifications yet': 'لا توجد إخطارات حتى الآن',
    'No pending email invites': '?? ???? ????? ???? ???????? ?????',
    'No pending requests right now': 'لا توجد طلبات معلقة في الوقت الحالي',
    'No recent camera update': '?? ???? ????? ???? ????????',
    'No unread notifications': 'لا توجد إخطارات غير مقروءة',
    'Not provided': 'غير متوفر',
    'Notification removed': 'تمت إزالة الإشعار',
    'Notifications about attendance, leaves, and system events will appear here.':
        'ستظهر هنا إشعارات حول الحضور والإجازات وأحداث النظام.',
    'Only user and admin accounts can create user groups. Ask a user or admin to create one or add you to an existing group.':
        'يمكن لحسابات المستخدمين والمسؤولين فقط إنشاء مجموعات مستخدمين. اطلب من مستخدم أو مسؤول إنشاء واحدة أو إضافتك إلى مجموعة موجودة.',
    'Only users and admins can access the export center.':
        'يمكن للمستخدمين والمسؤولين فقط الوصول إلى مركز التصدير.',
    'Open Batch Register': 'فتح سجل الدفعة',
    'Open Main Dashboard': 'افتح لوحة التحكم الرئيسية',
    'Passwords do not match': 'كلمات المرور غير متطابقة',
    'Paste your reset token here': 'الصق رمز إعادة التعيين هنا',
    'Pending Email Invites': '????? ?????? ?????????? ???????',
    'Pick a group and class to link them without leaving the dashboard.':
        'اختر مجموعة وفصلًا لربطهما دون مغادرة لوحة التحكم.',
    'Please confirm your new password':
        'الرجاء تأكيد كلمة المرور الجديدة الخاصة بك',
    'Please enter a new password': 'الرجاء إدخال كلمة مرور جديدة',
    'Please enter a valid email address': 'يرجى إدخال عنوان بريد إلكتروني صالح',
    'Please enter the reset token': 'الرجاء إدخال رمز إعادة التعيين',
    'Please enter your email address':
        'الرجاء إدخال عنوان البريد الإلكتروني الخاص بك',
    'Please provide a reason (min 5 characters)':
        'يرجى تقديم السبب (5 أحرف على الأقل)',
    'Profile updated successfully': 'تم تحديث الملف الشخصي بنجاح',
    'Public registration creates user accounts only. Admins should use Manage Users to create admin or user accounts, then sign in with the admin access key.':
        'التسجيل العام ينشئ حسابات المستخدمين فقط. يجب على المسؤولين استخدام "إدارة المستخدمين" لإنشاء حسابات إدارية أو مستخدمين، ثم تسجيل الدخول باستخدام مفتاح وصول المسؤول.',
    'Re-enter your new password': 'أعد إدخال كلمة المرور الجديدة',
    'Reason': 'سبب',
    'Recognition Confidence': '??????? ??????',
    'Registration failed': 'فشل التسجيل',
    'Rejected': 'مرفوض',
    'Reset Password': 'إعادة تعيين كلمة المرور',
    'Reset Token': 'إعادة تعيين الرمز المميز',
    'Reset Your Password': 'إعادة تعيين كلمة المرور الخاصة بك',
    'Retry': 'أعد المحاولة',
    'Review Request': 'طلب المراجعة',
    'Review note: {note}': 'ملاحظة المراجعة: {note}',
    'Review pending, approved, and rejected leave requests for this student.':
        'مراجعة طلبات الإجازة المعلقة والموافق عليها والمرفوضة لهذا الطالب.',
    'Review: {name}': 'مراجعة: {name}',
    'Reviewed by': 'تمت المراجعة بواسطة',
    'Reviewed by {name}': 'تمت المراجعة بواسطة {name}',
    'Scan Mode': '??? ?????',
    'Set New Password': 'تعيين كلمة مرور جديدة',
    'Settings saved successfully': 'تم حفظ الإعدادات بنجاح',
    'Show All': 'إظهار الكل',
    'Show Unread Only': 'إظهار غير المقروءة فقط',
    'Sign in to the admin dashboard with your access key':
        'قم بتسجيل الدخول إلى لوحة تحكم المشرف باستخدام مفتاح الوصول الخاص بك',
    'Student ID: {id}': 'معرف الطالب: {id}',
    'Student Profile': 'الملف الشخصي للطالب',
    'Students: {count}': 'الطلاب: {count}',
    'Submit Leave Request': 'إرسال طلب الإجازة',
    'Submitted {date} at {time}': 'تم تقديم {date} في {time}',
    'Submitted: {date}': 'المقدم: {date}',
    'System': 'نظام',
    'Team Members': '????? ??????',
    'This account is signed in as {role}. Only admin or super admin accounts can open the admin dashboard.':
        'تم تسجيل الدخول إلى هذا الحساب باسم {role}. يمكن فقط لحسابات المشرف أو المشرف المتميز فتح لوحة تحكم المشرف.',
    'Time': 'وقت',
    'Token copied': 'تم نسخ الرمز المميز',
    'Token pre-filled from backend response':
        'الرمز المميز مملوء مسبقًا من استجابة الواجهة الخلفية',
    'Undo': 'تراجع',
    'Use one workspace to manage members, email invites, and linked classes for the selected group.':
        'استخدم مساحة عمل واحدة لإدارة الأعضاء ودعوات البريد الإلكتروني والفصول الدراسية المرتبطة بالمجموعة المحددة.',
    'Verifying identity': '???? ?????? ?? ??????',
    'Write an optional note...': 'أكتب ملاحظة اختيارية...',
    'You can only invite users to groups you manage.':
        'يمكنك فقط دعوة المستخدمين إلى المجموعات التي تديرها.',
    'You have been marked late today at {time}.':
        'لقد تم وضع علامة عليك في وقت متأخر اليوم في {time}.',
    'Your attendance is {percent}%, which is below the {threshold}% threshold.':
        'حضورك هو {percent}%، وهو أقل من عتبة {threshold}%.',
    'Your leave request for {date} was {status}.':
        'طلب الإجازة الخاص بك لـ {date} كان {status}.',
    'Your leave request for {date} was {status}. Note: {note}':
        'طلب الإجازة الخاص بك لـ {date} كان {status}. ملحوظة: {note}',
    '{name} submitted a leave request for {date}.':
        'قدم {name} طلب إجازة لـ {date}.',
    'You were invited to join {group} as {role}.':
        'تمت دعوتك للانضمام إلى {group} بصفة {role}.',
    '{name} joined {group}.': 'انضم {name} إلى {group}.',
    '{name} rejected the invitation to {group}.':
        'رفض {name} الدعوة إلى {group}.',
    'Your supervision role in {group} is now {role}.':
        'أصبح دور الإشراف الخاص بك في {group} الآن {role}.',
  };

  static const Map<String, String> translations = {
    'appTitle': 'نظام الحضور بالتعرف على الوجه',
    'language': 'اللغة',
    'languageEnglish': 'الإنجليزية',
    'languageSorani': 'الكردية السورانية',
    'languageArabic': 'العربية',
    'splashTagline': 'سريع  •  آمن  •  آلي',
    'welcomeBack': 'مرحباً بعودتك',
    'signInTeacherDashboard': 'سجّل الدخول إلى لوحتك',
    'email': 'البريد الإلكتروني',
    'enterEmail': 'أدخل بريدك الإلكتروني',
    'emailRequired': 'البريد الإلكتروني مطلوب',
    'enterValidEmail': 'أدخل بريداً إلكترونياً صالحاً',
    'password': 'كلمة المرور',
    'enterPassword': 'أدخل كلمة المرور',
    'passwordRequired': 'كلمة المرور مطلوبة',
    'passwordMinLength': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    'rememberMe': 'تذكرني',
    'forgotPassword': 'هل نسيت كلمة المرور؟',
    'forgotPasswordTitle': 'نسيت كلمة المرور',
    'forgotPasswordHelp':
        'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.',
    'pleaseEnterEmail': 'يرجى إدخال البريد الإلكتروني',
    'pleaseEnterValidEmail': 'يرجى إدخال بريد إلكتروني صالح',
    'cancel': 'إلغاء',
    'sendResetLink': 'إرسال رابط إعادة التعيين',
    'passwordResetSent': 'تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني',
    'failedToSendResetLink': 'فشل إرسال رابط إعادة التعيين',
    'loginFailed': 'فشل تسجيل الدخول',
    'signIn': 'تسجيل الدخول',
    'dontHaveAccount': 'ليس لديك حساب؟',
    'signUp': 'إنشاء حساب',
    'teacherAttendanceSystem': 'نظام الحضور',
    'smartRoomScanning': 'مسح ذكي للقاعات',
    'processEntireHallsSeconds': 'معالجة القاعات بالكامل خلال ثوانٍ',
    'faceRecognition': 'التعرف على الوجه',
    'automatedStudentIdentification': 'تعرف آلي على الطلاب',
    'analyticsDashboard': 'لوحة التحليلات',
    'trackAttendanceTrends': 'تتبع اتجاهات الحضور',
    'dashboard': 'لوحة التحكم',
    'history': 'السجل',
    'profile': 'الملف الشخصي',
    'roomScanner': 'ماسح القاعة',
    'batchRegister': 'تسجيل جماعي',
    'notifications': 'الإشعارات',
    'leaveRequests': 'طلبات الإجازة',
    'management': 'الإدارة',
    'editAttendance': 'تعديل الحضور',
    'classes': 'الصفوف',
    'exportCenter': 'مركز التصدير',
    'adminPanel': 'لوحة الإدارة',
    'teacherPortal': 'بوابة الحضور',
    'collapse': 'تصغير',
    'signOut': 'تسجيل الخروج',
    'signOutTitle': 'تسجيل الخروج',
    'signOutConfirm': 'هل تريد تسجيل الخروج؟',
    'deleteAccountTitle': 'حذف الحساب',
    'deleteAccountConfirm':
        'هل تريد حذف حسابك نهائياً؟ سيؤدي ذلك إلى إزالة الصفوف والطلاب وسجلات الحضور والإشعارات.',
    'deleteAccountWarning': 'لا يمكن التراجع عن هذا الإجراء.',
    'deleteAccountFailed': 'فشل حذف الحساب',
    'user': 'المستخدم',
    'refresh': 'تحديث',
    'totalPresent': 'إجمالي الحضور',
    'totalLate': 'إجمالي المتأخرين',
    'totalAbsent': 'إجمالي الغياب',
    'attendanceRate': 'نسبة الحضور',
    'quickActions': 'إجراءات سريعة',
    'manageClasses': 'إدارة الصفوف',
    'fullHistory': 'السجل الكامل',
    'todaysStatus': 'حالة اليوم',
    'noAttendanceToday': 'لم يتم تسجيل حضور اليوم',
    'goodMorning': 'صباح الخير',
    'goodAfternoon': 'مساء الخير',
    'goodEvening': 'مساء الخير',
    'teacher': 'المستخدم',
    'admin': 'المشرف',
    'phone': 'الهاتف',
    'department': 'القسم',
    'faceRegistered': 'الوجه مسجل',
    'yes': 'نعم',
    'no': 'لا',
    'account': 'الحساب',
    'manageProfileSettings': 'أدر ملفك الشخصي وإعداداتك',
    'actions': 'الإجراءات',
    'editProfile': 'تعديل الملف الشخصي',
    'updateNamePhoneDepartment': 'حدّث الاسم والهاتف والقسم',
    'changePassword': 'تغيير كلمة المرور',
    'updateAccountPassword': 'حدّث كلمة مرور الحساب',
    'reregisterFace': 'إعادة تسجيل الوجه',
    'updateFaceData': 'حدّث بيانات التعرف على الوجه',
    'viewAttendanceUpdates': 'عرض تحديثات الحضور والنظام',
    'submitOrReviewLeave': 'إرسال أو مراجعة طلبات الإجازة',
    'adminDashboard': 'لوحة الإدارة',
    'manageUsersReportsSettings': 'إدارة المستخدمين والتقارير والإعدادات',
    'session': 'الجلسة',
    'notLoggedIn': 'لم يتم تسجيل الدخول',
    'guardianPortal': 'بوابة ولي الأمر',
    'guardianPortalPreview': 'معاينة بوابة ولي الأمر',
    'guardianPortalDescription':
        'استعرض تجربة الأسر من خلال الطلاب المرتبطين والتنبيهات والجداول القادمة.',
    'openGuardianPreview': 'فتح المعاينة',
    'featureLaunchpad': 'منصة الميزات',
    'featureLaunchpadDescription':
        'أطلق الجيل القادم من تدفقات الحضور مباشرة من الواجهة.',
    'realtimeUpdates': 'تحديثات فورية',
    'realtimeUpdatesDescription':
        'بطاقات بث جاهزة للويب سوكيت لأحداث الحضور ونشاط القاعات والتنبيهات التشغيلية.',
    'scheduleBuilder': 'منشئ الجدول',
    'scheduleBuilderDescription':
        'اسحب عبر الشبكة الأسبوعية لوضع حصة وتكرارها في الأيام المحددة.',
    'openClassBuilder': 'فتح منشئ الصفوف',
    'arabicSupport': 'دعم اللغة العربية',
    'arabicSupportDescription':
        'فعّل التسميات العربية واتجاه RTL والشاشات المحلية الموجهة للأسرة.',
    'switchToArabic': 'التحويل إلى العربية',
    'arabicActive': 'العربية مفعلة',
    'liveStreamTitle': 'بث الحضور الفوري',
    'liveStreamPollingFallback': 'تحديث حي بديل كل {seconds} ثانية',
    'liveStreamPaused': 'تم إيقاف البث المباشر',
    'liveStreamSelectToday': 'اختر تاريخ اليوم لمتابعة إشارات الحضور الفورية.',
    'socketReadyFallback':
        'الواجهة جاهزة للويب سوكيت، وتعمل حالياً عبر حلقة التحديث الحي الحالية.',
    'portalPreviewBanner':
        'تعتمد هذه المعاينة على بيانات الحضور والصفوف الحالية إلى أن يتم ربط واجهات برمجة التطبيقات الخاصة بأولياء الأمور.',
    'linkedLearners': 'الطلاب المرتبطون',
    'familyAlerts': 'تنبيهات الأسرة',
    'attendanceConfirmed': 'حضور مؤكد',
    'upcomingSessions': 'الحصص القادمة',
    'attendanceFeed': 'سجل نشاط الأسرة',
    'guardianPortalEmpty':
        'لا توجد حركة حضور حتى الآن. ستظهر تغذية الأسرة هنا بعد بدء تسجيل الطلاب.',
    'visualScheduleBuilder': 'منشئ الجدول المرئي',
    'visualScheduleBuilderDescription':
        'اسحب عبر الشبكة الأسبوعية لوضع حصة صفية. ثم فعّل الأيام لتكرار نفس الوقت خلال الأسبوع.',
    'schedulePreview': 'معاينة الجدول',
    'repeatOnDays': 'التكرار في الأيام',
    'selectedSchedule': 'الجدول المحدد',
    'classNameRequired': 'أدخل اسم الصف قبل الحفظ.',
    'scheduleRequired':
        'اختر يوماً واحداً على الأقل واسحب كتلة زمنية قبل الحفظ.',
    'scheduleBuilderHint':
        'اسحب عمودياً داخل أحد الأعمدة لوضع كتلة الصف في التقويم الأسبوعي.',
    'dashboardDestination': 'انتقل إلى بعد تسجيل الدخول',
    'chooseDashboardDestination':
        'اختر لوحة التحكم التي تريد فتحها بعد تسجيل الدخول',
    'registerDestination': 'الاستمرار في',
    'chooseRegisterDestination':
        'اختر ما إذا كنت تريد إنشاء حساب مستخدم أو حساب مسؤول',
    'mainDashboard': 'لوحة القيادة الرئيسية',
    'mainDashboardDescription': 'افتح شاشة الحضور الرئيسية',
    'adminDashboardDescription':
        'افتح لوحة تحكم المشرف لحسابات المشرف والمشرف المتميز',
    'adminDashboardAccessDenied': 'لا يمكن لهذا الحساب فتح لوحة تحكم المسؤول.',
    'pendingInvitationReviewPrompt': 'لديك دعوات مستخدمين معلقة للمراجعة.',
    'invitedBy': 'بدعوة من {name}',
    'adminAccountsUseSignIn': 'تسجيل المشرف يتطلب رمزا',
    'registerTeacherAccountNotice':
        'حدد خيار المسؤول، وأكمل النموذج، وأدخل رمز تسجيل المسؤول لإنشاء حساب مسؤول.',
    'signInToAdminDashboard': 'قم بتسجيل الدخول إلى لوحة تحكم المشرف',
    'createAdminAccount': 'إنشاء حساب المسؤول',
    'adminRegistrationCode': 'رمز تسجيل المشرف',
    'enterAdminRegistrationCode': 'أدخل رمز تسجيل المشرف',
    'adminRegistrationCodeRequired': 'مطلوب رمز تسجيل المشرف',
    'members': '???????',
    'supervisorHub': '???? ???????',
    'teacherGroups': '??????? ??????????',
    'createGroup': '????? ??????',
    'createTeacherGroup': '????? ?????? ????????',
    'groupName': '??? ????????',
    'groupDescription': '??? ????????',
    'inviteTeachers': '???? ??????????',
    'emailAddresses': '?????? ?????? ??????????',
    'emailAddressesHint':
        'أدخل واحدًا أو أكثر من رسائل البريد الإلكتروني للمستخدم مفصولة بفواصل أو أسطر جديدة',
    'teacherRole': '??? ????????',
    'superTeacher': '?????? ?????',
    'superAdmin': 'المشرف الفائق',
    'pendingInvitations': '??????? ???????',
    'pendingLeaves': '????? ??????? ???????',
    'yourInvitations': '??????',
    'shareClassWithGroup': '?????? ???? ?? ????????',
    'shareClass': '?????? ????',
    'selectGroup': '???? ????????',
    'selectClass': '???? ????',
    'openLeaveRequests': '??? ????? ???????',
    'groupCreated': '?? ????? ?????? ??????????',
    'teachersInvited': '?? ????? ????? ??????????',
    'classShared': 'تمت مشاركة الفصل مع المجموعة',
    'roleUpdated': '?? ????? ??? ????????',
    'noTeacherGroups': '?? ???? ??????? ???????? ??? ????',
    'noMembersYet': 'لم تتم إضافة أي أعضاء حتى الآن',
    'noSharedClasses': 'لا توجد فصول مشتركة حتى الآن',
    'noPendingLeaves': 'لا توجد طلبات إجازة معلقة',
    'noSupervisionData': '?? ???? ?????? ????? ?????.',
    'sendInvite': '????? ??????',
    'noteOptional': '?????? (???????)',
    'enterAtLeastOneEmail': 'أدخل بريدًا إلكترونيًا واحدًا على الأقل للمستخدم',
    'selectGroupAndClass': 'حدد المجموعة والفصل أولاً',
    'invitationAccepted': 'تم قبول الدعوة',
    'invitationRejected': 'تم رفض الدعوة',
    'makeSuperTeacher': 'جعل المستخدم الفائق',
    'setAsTeacher': 'تعيين كمستخدم',
    'operationFailed': '???? ???????',
    'accept': '????',
    'reject': '???',
    'systemSettings': 'إعدادات النظام',
    'save': 'يحفظ',
    'reloadFromServer': 'إعادة التحميل من الخادم',
    'unsavedChanges': 'لديك تغييرات غير محفوظة',
    'appearance': 'مظهر',
    'backendConnection': 'اتصال الخلفية',
    'apiBaseUrl': 'عنوان URL الأساسي لواجهة برمجة التطبيقات',
    'test': 'امتحان',
    'apply': 'يتقدم',
    'connectedHealthy': 'متصل! الخادم سليم .',
    'serverRespondedWithStatus': 'استجاب الخادم بالحالة {code}',
    'failedToConnect': 'فشل الاتصال: {reason}',
    'urlResetDefault': 'إعادة تعيين عنوان URL إلى الوضع الافتراضي',
    'resetToDefault': 'إعادة التعيين إلى عنوان URL الافتراضي',
    'attendanceTime': 'وقت الحضور',
    'lateCheckInThreshold': 'عتبة تسجيل الوصول المتأخر',
    'studentsArrivingLate':
        'يتم وضع علامة متأخر على الطلاب الذين يصلون بعد هذا الوقت',
    'attendanceAlertThreshold': 'عتبة تنبيه الحضور',
    'notifyWhenAttendanceBelow': 'إعلام عندما يقل الحضور عن هذه النسبة',
    'attendanceMethods': 'طرق الحضور',
    'allowAttendanceFace': 'السماح بالحضور عبر التعرف على الوجه',
    'qrCodeAttendance': 'الحضور رمز الاستجابة السريعة',
    'allowAttendanceQr': 'السماح بالحضور عبر مسح رمز الاستجابة السريعة',
    'manualEntry': 'الإدخال اليدوي',
    'allowTeachersManual': 'السماح بإدخال الحضور اليدوي',
    'faceRegistration': 'تسجيل الوجه',
    'minimumFaceImages': 'الحد الأدنى من صور الوجه',
    'minimumPhotosRequired': 'الحد الأدنى من الصور المطلوبة لتسجيل الوجه',
    'maximumFaceImages': 'الحد الأقصى لصور الوجه',
    'maximumPhotosAllowed': 'الحد الأقصى للصور المسموح بها للتسجيل',
    'qrSession': 'جلسة QR',
    'sessionDuration': 'مدة الجلسة',
    'minutesActive': 'كم دقيقة تبقى جلسة QR نشطة',
    'application': 'طلب',
    'appName': 'اسم التطبيق',
    'displayNameShown': 'اسم العرض الموضح في التطبيق',
    'saving': 'توفير...',
    'saveAllSettings': 'حفظ كافة الإعدادات',
    'discardChanges': 'تجاهل التغييرات',
    'darkMode': 'الوضع المظلم',
    'lightMode': 'وضع الضوء',
    'toggleTheme': 'التبديل بين المظهر الداكن والخفيف',
    'backendUrlUpdated':
        'تم تحديث عنوان URL للواجهة الخلفية. أعد تشغيل التطبيق للتطبيق بالكامل.',
    'checkOut': 'الدفع',
    'checkOutDescription':
        'حدد وقت تسجيل المغادرة باستخدام ميزة التعرف على الوجه',
    'checkingOut': 'التحقق من...',
    'checkOutSuccess': 'تم السحب بنجاح!',
    'checkOutFailed': 'فشل تسجيل الخروج',
    'alreadyCheckedOut': 'تم تسجيل الخروج بالفعل اليوم',
    'noCheckInFound': 'لم يتم العثور على تسجيل الوصول لهذا اليوم',
    'qrAttendance': 'الحضور QR',
    'qrAttendanceDescription': 'إنشاء رمز الاستجابة السريعة للحضور',
    'createQrSession': 'إنشاء جلسة QR',
    'scanQrCode': 'مسح رمز الاستجابة السريعة',
    'qrSessionCreated': 'تم إنشاء جلسة QR!',
    'qrSessionActive': 'جلسة QR نشطة',
    'qrSessionExpired': 'انتهت صلاحية جلسة QR',
    'qrCode': 'رمز الاستجابة السريعة',
    'copyQrCode': 'انسخ رمز الاستجابة السريعة',
    'qrSessionMins': 'دقائق',
    'qrActive': 'نشيط',
    'qrExpired': 'منتهي الصلاحية',
    'deactivateSession': 'إلغاء التنشيط',
    'examProctoring': 'مراقبة الامتحان',
    'examProctoringDescription': 'مراقبة الامتحانات للغش',
    'startProctoring': 'ابدأ بالمراقبة',
    'stopProctoring': 'توقف عن المراقبة',
    'studentVerified': 'تم التحقق من الطالب',
    'studentNotVerified': 'لم يتم التحقق من الطالب',
    'faceCount': 'عدد الوجه',
    'gazeDirection': 'اتجاه النظرة',
    'suspicionScore': 'درجة الشكوك',
    'violations': 'الانتهاكات',
    'cheatingDetected': 'تم اكتشاف الغش',
    'noViolations': 'لا توجد انتهاكات',
    'rollCall': 'رول كول',
    'rollCallDescription': 'نداء الأسماء اليدوي للفصل بأكمله',
    'selectAll': 'حدد الكل',
    'deselectAll': 'قم بإلغاء تحديد الكل',
    'submitRollCall': 'إرسال رول كول',
    'rollCallComplete': 'اكتملت المكالمة الهاتفية',
    'analytics': 'التحليلات',
    'analyticsDescription': 'عرض تحليلات الحضور والرسوم البيانية',
    'dailyTrend': 'الاتجاه اليومي',
    'departmentBreakdown': 'انهيار القسم',
    'methodBreakdown': 'انهيار الطريقة',
    'attendanceTrend': 'اتجاه الحضور',
    'last30Days': 'آخر 30 يومًا',
    'last7Days': 'آخر 7 أيام',
    'last90Days': 'آخر 90 يومًا',
    'auditLog': 'سجل التدقيق',
    'auditLogDescription': 'عرض مسار تدقيق النظام',
    'logAction': 'فعل',
    'actor': 'ممثل',
    'target': 'هدف',
    'ipAddress': 'عنوان IP',
    'noAuditLogs': 'لم يتم العثور على سجلات التدقيق',
    'bulkImport': 'استيراد بالجملة',
    'bulkImportStudents': 'طلاب الاستيراد بالجملة',
    'importFromCsv': 'استيراد من CSV',
    'selectCsvFile': 'حدد ملف CSV',
    'csvFormat': 'تنسيق CSV',
    'csvFormatHelp': 'يجب أن يحتوي ملف CSV على عمود "اسم" يتضمن أسماء الطلاب',
    'importing': 'جارٍ الاستيراد...',
    'importSuccess': 'تم الاستيراد بنجاح!',
    'importFailed': 'فشل الاستيراد',
    'studentsImported': 'الطلاب المستوردة',
    'errorsFound': 'تم العثور على أخطاء',
    'deleteAccount': 'حذف الحساب',
    'deleteAccountDescription': 'حذف حسابك نهائيًا',
    'removeFace': 'إزالة الوجه',
    'removeFaceDescription': 'إزالة تسجيل وجهك',
    'faceRemoved': 'تمت إزالة تسجيل الوجه',
    'confirmRemoveFace': 'هل أنت متأكد أنك تريد إزالة تسجيل وجهك؟',
    'deleteNotification': 'حذف الإخطار',
    'notificationDeleted': 'تم حذف الإشعار',
    'settingsDescription': 'إدارة إعدادات النظام',
    'lateThreshold': 'عتبة متأخرة',
    'alertThreshold': 'عتبة التنبيه',
    'minFaceImages': 'صور الوجه دقيقة',
    'maxFaceImages': 'صور ماكس الوجه',
    'qrDuration': 'مدة الاستجابة السريعة',
    'allowFace': 'السماح للوجه',
    'allowQr': 'السماح بـ QR',
    'allowManual': 'السماح بالدليل',
    'saveSettings': 'حفظ الإعدادات',
    'settingsSaved': 'تم حفظ الإعدادات!',
    'notes': 'ملحوظات',
    'viewNotes': 'عرض الملاحظات',
    'addNotes': 'أضف ملاحظات',
    'openGroup': 'فتح المجموعة',
    'userGroupInvitationTitle': 'دعوة مجموعة المستخدمين',
    'userInvitationAcceptedTitle': 'تم قبول دعوة المستخدم',
    'userInvitationRejectedTitle': 'تم رفض دعوة المستخدم',
    'supervisorAccessUpdatedTitle': 'تم تحديث صلاحية الإشراف',
  };
}
